import React from 'react'

function Attendance() {
  return (
    <div>
      This is Attendance Component
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur quos enim illum optio! Molestiae, temporibus? Atque repudiandae aliquid ducimus natus laudantium, accusamus ratione libero neque deserunt quia sed laborum reiciendis, incidunt consequuntur! Nobis reiciendis eum, quos illum est impedit minima neque cumque odio. Fugiat dolor esse reiciendis magni quisquam autem nesciunt nostrum inventore reprehenderit similique, alias nulla incidunt magnam! Repellat suscipit fuga, nemo laudantium amet cum laboriosam! Numquam pariatur rem quasi similique accusantium ullam nihil. Ullam recusandae impedit, quo animi eius debitis vel velit nulla ducimus magnam necessitatibus accusantium expedita sint veritatis aut rem aliquam qui a tempore! Iure maiores esse optio aliquid nobis modi iste, vitae commodi atque quibusdam est quisquam ea facilis porro, unde itaque a voluptatem error velit necessitatibus corrupti harum? Ad, tempore vero exercitationem saepe cupiditate, aperiam sunt excepturi quos sint eveniet eius, quae minima accusantium. Debitis porro hic explicabo perspiciatis obcaecati laboriosam eligendi maxime accusamus. Animi fugit ex fuga aliquam necessitatibus! Animi veniam unde adipisci itaque molestias, ipsam eveniet laboriosam? Sed facere ipsa, soluta accusantium atque doloremque similique quam fuga officiis! Eaque distinctio quae rem explicabo quo nesciunt numquam nam velit nihil optio, est incidunt voluptatibus cupiditate id sint qui! Dignissimos consequuntur laudantium rem sit maiores perferendis nemo harum minima, iusto quae dolorem optio voluptates, amet repellat! Temporibus repudiandae consequatur, ea ullam veniam reiciendis aut obcaecati earum, cum maxime nulla eius provident vitae blanditiis similique tenetur quod esse, porro expedita sunt error vero officiis? Eum at, inventore quibusdam voluptates blanditiis omnis atque aspernatur reprehenderit minus labore? Dolorem atque nihil quasi. Omnis voluptate ea sint incidunt, optio ipsa aliquam aliquid quae quasi eos minima repellendus consectetur facere esse reprehenderit molestiae fugiat officiis alias. Sunt esse, sit atque temporibus totam nostrum doloribus, quod ea magnam incidunt distinctio vero doloremque nobis sint laudantium reprehenderit adipisci culpa eligendi, quidem enim ad corrupti eum possimus illum. Sed voluptatum autem in rerum hic repellat aperiam tempora nam libero sequi, sint ad assumenda, enim quasi cumque? Accusamus earum doloribus eveniet nostrum illo nesciunt tempora? Nemo commodi rerum impedit tempora, inventore, doloremque dolorum sunt vero adipisci fuga aspernatur officiis. Doloremque molestiae cupiditate sit fuga velit? Veritatis totam unde illo sapiente assumenda, ipsa vero quos iusto ab voluptas, neque ullam dolor amet, nemo sit debitis? Rem, atque numquam. Qui consequuntur saepe totam corporis veritatis ipsum voluptatibus eum doloribus illum cum natus voluptatum exercitationem molestiae temporibus nulla error itaque nemo illo dolores id, neque reiciendis.
    </div>
  )
}

export default Attendance
